name = "tts-service"
main = "index.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "TTS", class_name = "TTSState" }
]

[[migrations]]
tag = "v1"
new_classes = ["TTSState"] 